version: '3.8'
services:
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ubti_schema
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile.api
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ubti_schema
#      SPRING_DATASOURCE_USERNAME: appuser
#      SPRING_DATASOURCE_PASSWORD: appuser
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db
volumes:
  db_data: { }